apiVersion: v1
kind: ConfigMap
metadata:
  name: rkubelog-env
binaryData:
  PAPERTRAIL_PROTOCOL: {{ .Values.papertrail.protocol | b64enc }}
  PAPERTRAIL_HOST: {{ .Values.papertrail.host | b64enc }}
  PAPERTRAIL_PORT: {{ .Values.papertrail.port | toString | b64enc }}
  LOGGLY_TOKEN: "{{ .Values.loggly.token | b64enc }}"
  TAGS: "{{ .Values.tags | b64enc }}"