# Copyright 2019 SolarWinds Worldwide, LLC.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "rkubelog"
  labels:
    app: rkubelog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rkubelog
  template:
    metadata:
      labels:
        kail.ignore: "true"
        app: rkubelog
    spec:
    {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
      serviceAccountName: rkubelog-sa
      containers:
      - image: "{{ .Values.dockerImage }}"
        imagePullPolicy: Always
        name: "rkubelog"
        command:
        - /app/rkubelog
        args:
{{ toYaml .Values.arguments | indent 10 }}
        envFrom:
          - configMapRef:
              name: "rkubelog-env"
        {{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        {{- end }}
