# Copyright 2019 SolarWinds Worldwide, LLC.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "rkubelog"
  labels:
    app: rkubelog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rkubelog
  template:
    metadata:
      labels:
        kail.ignore: "true"
        app: rkubelog
    spec:
      serviceAccountName: rkubelog-sa
      containers:
      - image: "{{ .Values.dockerImage }}"
        imagePullPolicy: Always
        name: "rkubelog"
        command:
        - /app/rkubelog
        envFrom:
          - configMapRef:
              name: "rkubelog-env"
