dockerImage: "quay.io/solarwinds/rkubelog:r18"

# Static tags which will get sent with all the logs.
# If you are using several instances of `rKubeLog`, you can use this `TAGS` field to differentiate between the logs from the different environments.
tags: ""

# Leave those empty to disable Papertrail
papertrail:
  # Acceptable values are udp, tcp, tls. This also depends on the choices that are selected under the `Destination Settings`; by default, a new destination accepts TLS and UDP connections.
  protocol: tls
  # Log destination host
  host: ""
  # Log destination port
  port: ""

loggly:
  # Leave empty to disable Loggly
  token: ""

resources: {}

affinity: {}

arguments: []
