# Copyright 2019 SolarWinds Worldwide, LLC.
# SPDX-License-Identifier: Apache-2.0

name: rkubelog
on:
  push:
    branches:
      - '*'
    paths-ignore:
      - 'README.md'
      - 'SECURITY.md'
      - 'LICENSE'
      - 'rkubelog/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'SECURITY.md'
      - 'LICENSE'
      - 'rkubelog/**'

env:
  IMAGE_NAME: "quay.io/solarwinds/rkubelog"

jobs:
  checks:
    name: Static checks
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: golangci/golangci-lint-action@v2.3.0
      with:
        version: v1.35
        args: --allow-parallel-runners --timeout 3m ./...
  build:
    name: build check
    runs-on: ubuntu-latest
    needs: [checks]
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - run: make build
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Docker build
        run: |
          DOCKER_BUILDKIT=1 docker build --no-cache -t ${{ env.IMAGE_NAME }}:latest .
          docker manifest inspect ‐‐verbose ${{ env.IMAGE_NAME }}:latest